"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { useParams } from "next/navigation";
import CallRoutingEditor from "@/components/settings/markets/call-routing-editor";
import VoicemailGreetingEditor from "@/components/settings/markets/voicemail-greeting-editor";

type Market = { id: string; name: string; purpose: "campaign" | "main"; numberCount: number; call_routing_mode: "browser_only"|"browser_first_then_forward"|"forwarding_only"; browser_ring_timeout_seconds: number; call_forwarding_number: string | null; voicemail_greeting_url: string | null; voicemail_greeting_source: "polly"|"recorded"|null };
type NumberItem = { e164: string; label: string | null; config_override: boolean; call_routing_mode: "browser_only"|"browser_first_then_forward"|"forwarding_only"; browser_ring_timeout_seconds: number; call_forwarding_number: string | null; voicemail_greeting_url: string | null; voicemail_greeting_source: "polly"|"recorded"|null };
export default function MarketDetailPage(){const {id}=useParams<{id:string}>(); const [market,setMarket]=useState<Market|null>(null); const [numbers,setNumbers]=useState<NumberItem[]>([]); const overrideCount=useMemo(()=>numbers.filter(n=>n.config_override).length,[numbers]);
useEffect(()=>{fetch(`/api/markets/${id}`).then(r=>r.json()).then(d=>setMarket(d.market)); fetch(`/api/markets/${id}/numbers`).then(r=>r.json()).then(d=>setNumbers(d.numbers??[]));},[id]);
if(!market) return <div className="p-8">Loading...</div>;
return <div className="p-8 space-y-6"><Link href="/settings/markets" className="text-sm text-emerald-700">← Back to Markets</Link><h1 className="text-3xl font-semibold">{market.name}</h1><p className="text-sm text-muted-foreground">{market.numberCount} numbers in this market</p>{market.purpose === "campaign" && <div className="space-y-4"><CallRoutingEditor scopeId={market.id} patchEndpoint={`/api/markets/${id}`} callRoutingMode={market.call_routing_mode} browserRingTimeoutSeconds={market.browser_ring_timeout_seconds} callForwardingNumber={market.call_forwarding_number} onSaved={(next)=>setMarket((m)=>m?{...m,...next}:m)} /><VoicemailGreetingEditor scopeId={market.id} scopeType="market" generateEndpoint="/api/markets/greeting/generate" patchEndpoint={`/api/markets/${id}`} currentUrl={market.voicemail_greeting_url} currentSource={market.voicemail_greeting_source} voices={[{id:"Danielle",label:"Danielle",engine:"long-form"}]} onSaved={(url,source)=>setMarket((m)=>m?{...m,voicemail_greeting_url:url,voicemail_greeting_source:source}:m)} onRemoved={()=>setMarket((m)=>m?{...m,voicemail_greeting_url:null,voicemail_greeting_source:null}:m)} /><details><summary>Override per number ({overrideCount})</summary>{numbers.map((n)=><div key={n.e164} className="mt-3 rounded border p-3"><label className="flex items-center gap-2"><input type="checkbox" checked={n.config_override} onChange={async(e)=>{await fetch(`/api/markets/numbers/${encodeURIComponent(n.e164)}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({config_override:e.target.checked})}); setNumbers((prev)=>prev.map(p=>p.e164===n.e164?{...p,config_override:e.target.checked}:p));}} />{n.label || n.e164}</label></div>)}</details></div>}{market.purpose === "main" && <div className="space-y-4"><details open><summary>Numbers in this market</summary>{numbers.map((n)=><details key={n.e164} className="mt-3 rounded border p-3"><summary>{n.label || n.e164}</summary><CallRoutingEditor scopeId={n.e164} patchEndpoint={`/api/markets/numbers/${encodeURIComponent(n.e164)}`} callRoutingMode={n.call_routing_mode} browserRingTimeoutSeconds={n.browser_ring_timeout_seconds} callForwardingNumber={n.call_forwarding_number} onSaved={()=>{}} /><VoicemailGreetingEditor scopeId={n.e164} scopeType="number" generateEndpoint="/api/markets/greeting/generate" patchEndpoint={`/api/markets/numbers/${encodeURIComponent(n.e164)}`} currentUrl={n.voicemail_greeting_url} currentSource={n.voicemail_greeting_source} voices={[{id:"Danielle",label:"Danielle",engine:"long-form"}]} onSaved={()=>{}} onRemoved={()=>{}} /></details>)}</details><details><summary>Set market default (optional)</summary><p className="text-sm text-muted-foreground">Numbers with per-number config above use their own settings. This is the fallback if you turn a number&apos;s per-number config off.</p></details></div>}</div>; }
