"use client";
import { useEffect, useState } from "react";
import Link from "next/link";

type Market = { id: string; name: string; purpose: "campaign" | "main"; numberCount: number; call_routing_mode: string | null; voicemail_greeting_source: string | null };
export default function MarketsPage() { const [markets, setMarkets] = useState<Market[]>([]); const [name, setName] = useState(""); const [purpose, setPurpose] = useState<"campaign"|"main">("campaign");
  useEffect(()=>{fetch("/api/markets").then(r=>r.json()).then(d=>setMarkets(d.markets??[]));},[]);
  async function create() { const res=await fetch("/api/markets",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,purpose})}); const d=await res.json(); if(d?.market?.id) window.location.href=`/settings/markets/${d.market.id}`; }
  return <div className="p-8 space-y-6"><div className="flex items-center justify-between"><div><h1 className="text-3xl font-semibold">Markets</h1><p className="text-muted-foreground">Group your numbers and configure routing & voicemail once per market.</p></div><div className="flex gap-2"><input className="rounded border p-2" placeholder="Name" value={name} onChange={(e)=>setName(e.target.value)} /><select className="rounded border p-2" value={purpose} onChange={(e)=>setPurpose(e.target.value as "campaign"|"main")}><option value="campaign">Campaign</option><option value="main">Main</option></select><button onClick={create} className="rounded bg-emerald-600 px-3 py-2 text-white">New market</button></div></div><div className="grid grid-cols-1 gap-4 md:grid-cols-2">{markets.map((m)=><Link key={m.id} href={`/settings/markets/${m.id}`} className="cursor-pointer rounded-xl border border-emerald-200 bg-white p-5 hover:border-emerald-400"><div className="flex items-center justify-between"><h3 className="font-semibold">{m.name}</h3><span className="text-xs rounded-full bg-emerald-50 px-2 py-1 text-emerald-700">{m.purpose}</span></div><p className="text-sm text-muted-foreground">{m.numberCount} numbers</p></Link>)}<button className="rounded-xl border border-dashed p-6 text-left">+ New market</button></div></div>; }
