import type { PersonaContent, SitePersona } from "../types"

// Buyer-acquisition / list-building copy. The site owner is a
// wholesaler/investor/agent building a buyer list; the visitor is the buyer.
// Render-time tokens: {Brand} (the business name) and {City} (the market, which
// falls back to "your area" on nationwide sites). Never write a literal city or
// state — only {City}.
export const PERSONAS: Record<SitePersona, PersonaContent> = {
  cash: {
    label: "Cash buyers",
    eyebrow: "Off-market cash deals",
    headline: "Off-market wholesale deals in {City} — sent to cash buyers first.",
    subhead:
      "Join {Brand}'s cash buyers list and get new off-market and wholesale properties — 30 to 50% under retail — the moment we lock them up. By text and email. Free to join.",
    stat: "New off-market deals, sent first",
    formTitle: "Get deals sent to you",
    formSubtitle: "New off-market properties, by text and email.",
    ctaLabel: "Send me deals",
    bannerCta: "Join the buyers list",
    features: [
      { icon: "🏠", title: "Off-market access", body: "Deals direct from distressed sellers, probate, and tax-delinquent owners — never on the MLS." },
      { icon: "⚡", title: "You move first", body: "Cash buyers on the list get every new deal by text and email the moment we lock it up. First to reply, first to lock it." },
      { icon: "💵", title: "Free to join", body: "No fees, no contracts. We make our money on the deals, not on the list." },
    ],
    announcement: "New off-market deals in {City} every week — join free and get them first.",
    howItWorks: [
      { title: "Join the list", body: "Drop your name and number. It takes 30 seconds and it's free." },
      { title: "Get deals by text and email", body: "We text and email you new properties with the price, repairs, and ARV already run." },
      { title: "Lock it up", body: "See one you like? Reply and we hand you the contract. Close fast, all cash." },
    ],
    faqs: [
      { q: "Is it really free to join?", a: "Yes. No fee, no subscription, no contract. We make our money on the deals we wholesale, not on the list." },
      { q: "Do I have to buy anything?", a: "Never. You'll get deals as we lock them up; buy when one fits your numbers and ignore the rest." },
      { q: "How fast do I need to act?", a: "The best deals move quickly, so being on the list and replying fast is the edge. We always give you the numbers up front so you can decide." },
      { q: "What kind of properties do you send?", a: "Mostly off-market single-family homes that need work — flips and rentals — plus the occasional multifamily, direct from motivated sellers." },
      { q: "Do I need to be a cash buyer?", a: "Cash and hard money close fastest and get first look. If you fund another way, tell us and we'll send deals you can actually close." },
      { q: "How do I get off the list?", a: "Reply STOP to any text and you're out instantly. Re-join anytime." },
    ],
    about: {
      headline: "We find the deals. You buy them right.",
      body: "{Brand} is a wholesale team that locks up off-market properties across {City} and the surrounding area, then passes them straight to our cash buyers list — no retail markup, no bidding wars, just clean deals with real spread for serious buyers. We'd rather send you one deal you actually close than flood you with junk.",
      trust: ["Numbers you can trust", "We close on time", "Built for repeat buyers"],
    },
    prose: [
      {
        eyebrow: "Why {Brand}",
        heading: "Off-market wholesale deals in {City}, before they ever hit the MLS.",
        bodyHtml: `<p>The wholesale deals worth buying rarely make it to the MLS. By the time a property in {City} is publicly listed, a dozen buyers have already seen it, the price has been bid up, and the spread that made it a deal is gone. <b>{Brand}</b> works the other side of that market — the off-market side — so the cash buyers on our list see real <b>off-market wholesale deals in {City}</b> before anyone else does.</p><p>Here's how it works in practice. We spend our days finding <b>motivated sellers</b> across the area — owners in pre-foreclosure, inherited and probate properties, tax-delinquent homes, and burnt-out landlords ready to walk away. We lock the property up under contract, run the numbers ourselves, and then text and email the deal straight to our <b>cash buyers list</b> with the asking price, the estimated repairs, and the after-repair value (ARV) already laid out. These are <b>wholesale properties priced 30 to 50% under retail</b> — the kind of <b>discount investment properties in {City}</b> that move in hours, not weeks.</p><h3>Built for cash buyers and flippers who move fast</h3><p>Because we've already done the underwriting, you can evaluate a deal in minutes instead of spending your weekend pulling comps. Whether you <b>fix and flip</b>, BRRRR, or buy and hold rentals, every property we send includes the spread up front so you can decide fast and lock it up. Cash and hard-money buyers get first look because they close fastest — but if you fund another way, tell us and we'll match you to deals you can actually close. It's free to join, no contract, and we make our money on the wholesale spread, not on you. <a href="/how-it-works">See exactly how it works</a>, or <a href="/properties">browse this week's off-market properties in {City} →</a>.</p>`,
        pullQuote: "We'd rather send you one deal you actually close than flood you with junk.",
      },
      {
        eyebrow: "Buying in {City}",
        heading: "Why {City} is one of the best markets to buy off-market deals.",
        bodyHtml: `<p>Strong rental demand, steady motivated-seller volume, and neighborhoods at every price point make {City} a productive market for cash buyers and flippers. The hard part is finding the <b>off-market deals in {City}</b> before they're ever listed — which is the whole job we do for you.</p><h3>Where the deals come from</h3><p>Motivated sellers are everywhere. We pull <b>distressed and discount properties</b> from owners facing foreclosure, probate, and back taxes, plus tired landlords offloading rentals off-market. Closer in, that's flips with strong resale comps; further out, <b>rental properties in {City}</b> that cash-flow from day one. Every new deal posts to the list the moment we lock it up — <a href="/properties">browse this week's wholesale and discount properties for sale →</a></p><h3>Why off-market beats the MLS</h3><p>On the MLS, a deal worth buying gets picked over by a dozen investors before you ever see it, and the margin's already gone. Off-market is the opposite — you're one of a handful of cash buyers who even know the property exists, the price already reflects the discount, and no bidding war eats your spread. That's the entire reason the list exists: to put you first. Tell us your buy box and we'll only send deals that fit. <a href="/get-on-the-list">Get on the cash buyers list for {City} — it's free →</a></p>`,
      },
    ],
    types: [
      { title: "Wholesale properties", body: "Locked-up deals we assign to you with real spread, 30–50% under retail.", href: "/properties" },
      { title: "Bank-owned & REO properties", body: "Bank-owned homes and REO deals priced to move, off-market where we can get them.", href: "/properties" },
      { title: "Foreclosure properties", body: "Pre-foreclosure and foreclosure homes from owners who need to sell fast.", href: "/properties" },
      { title: "Fixer-uppers & distressed", body: "Off-market homes that need work — the bread and butter of a good flip.", href: "/properties" },
      { title: "Probate & inherited homes", body: "Off-market homes from estates and inherited owners — often the deepest discounts.", href: "/properties" },
      { title: "Buy-and-hold rentals", body: "Off-market single-family and small multifamily in {City} that cash-flow.", href: "/properties" },
    ],
    situations: {
      heading: "The situations we buy in {City}",
      intro: "Most of our off-market deals come from owners who need to sell fast for reasons that never make it onto the MLS. These are the situations that produce the deepest discounts.",
      items: [
        { icon: "🏛️", title: "Foreclosure & pre-foreclosure", body: "Owners behind on payments who need to sell before the auction — often the most motivated, and the deepest spread.", href: "/properties" },
        { icon: "📜", title: "Probate & inherited homes", body: "Heirs who inherited a house they don't want to manage or repair, and would rather take a clean cash offer.", href: "/properties" },
        { icon: "🧾", title: "Tax-delinquent properties", body: "Owners facing back-tax pressure who need out fast — frequently vacant and well below market.", href: "/properties" },
        { icon: "🔑", title: "Tired & out-of-state landlords", body: "Burnt-out landlords done with tenants and repairs, selling rentals off-market at a discount.", href: "/properties" },
        { icon: "🛠️", title: "Distressed & fixer-uppers", body: "Homes too rough for a retail sale — code violations, fire, water, deferred maintenance — perfect for a flip.", href: "/properties" },
        { icon: "🏚️", title: "Vacant & code-violation homes", body: "Empty properties costing the owner money every month, where a fast cash close is the easiest exit.", href: "/properties" },
      ],
    },
    areas: {
      heading: "Where we find deals",
      intro: "We lock up off-market deals across {City} and nearby — browse by area:",
      singleLine: "We find off-market deals throughout {City} and the surrounding area.",
    },
    trustBar: [
      { value: "$0", label: "Fees to join" },
      { value: "<24h", label: "New deals to your inbox" },
      { value: "All cash", label: "Fast, certain closings" },
      { value: "Off-market", label: "Deals you won't find online" },
    ],
  },
  investor: {
    label: "Investor buyers",
    eyebrow: "Off-market investment deals",
    headline: "Investment properties in {City} with the spread already run — before they hit the market.",
    subhead:
      "{Brand} sends underwritten off-market flips and rentals to our investor list first. ARV, rehab, and spread done for you — so you can say yes in ten minutes, not ten days.",
    stat: "Underwritten deals, matched to your buy box",
    formTitle: "Get investment deals sent to you",
    formSubtitle: "Off-market flips and rentals, by text and email.",
    ctaLabel: "Send me deals",
    bannerCta: "Join the investor list",
    features: [
      { icon: "📊", title: "The math is already done", body: "Every deal lands with comps, rehab estimate, ARV, and the spread. Underwrite it in minutes, or pass and wait for the next." },
      { icon: "🥇", title: "You get first look", body: "Our list sees off-market flips and rentals before they reach the MLS or the rest of the market. First in, first to lock it." },
      { icon: "📈", title: "Equity on day one", body: "We negotiate the discount before you ever see it. You close with built-in equity, not a bidding war that eats your margin." },
    ],
    announcement: "New underwritten investment properties in {City} every week — investor list gets them first.",
    howItWorks: [
      { title: "Tell us your buy box", body: "Flip or hold, price range, areas, property type. Thirty seconds and you're in." },
      { title: "Get matched deals by text and email", body: "We send off-market investment properties that fit your box, with the numbers already run." },
      { title: "Lock it up and close", body: "Reply to claim it. We hand you a clean, title-ready contract and you close fast — cash or your lender." },
    ],
    faqs: [
      { q: "Are these real deals or just leads?", a: "Real, locked-up properties — we control them before we send them. Every one comes with comps, rehab, and ARV so you can verify the spread yourself." },
      { q: "How do you underwrite them?", a: "We pull recent comps, estimate the rehab, and set a conservative ARV before anything goes out. You see all of it and run your own return." },
      { q: "Do I have to be a cash buyer?", a: "No. Cash and hard money close fastest and get first look, but tell us how you fund and we'll match deals you can actually close." },
      { q: "What's the catch — is there a fee?", a: "None. The list is free, no contract. We make our money on the wholesale spread baked into the deal, never on you." },
      { q: "What kind of returns are these?", a: "It depends on the deal and your strategy. We don't promise numbers — we show you the spread and ARV on every property so you decide before you commit." },
      { q: "How do I stop the texts?", a: "Reply STOP to any message and you're off instantly. Re-join whenever you want." },
    ],
    about: {
      headline: "Deals that actually pencil — sent to investors who close.",
      body: "{Brand} sources off-market flips and rentals across {City} and the surrounding area, then underwrites every one before it reaches you — comps, rehab, ARV, and spread. We keep a tight list of serious investors on purpose: reliable closers earn the best deals first. We'd rather send you one property you actually fund than bury you in listings that don't work.",
      trust: ["Underwriting on every deal", "We close on time", "Built for repeat buyers"],
    },
    prose: [
      {
        eyebrow: "Why {Brand}",
        heading: "Off-market investment properties in {City}, with the numbers already run.",
        bodyHtml: `<p>By the time a real <b>investment property</b> hits the MLS in {City}, the margin is usually gone — picked over by a dozen buyers before you ever get a showing. {Brand} works the other side of the market. We source off-market <b>fix-and-flip</b> and <b>rental</b> deals straight from motivated sellers, probate, and tax-delinquent owners, then underwrite each one before it goes out: recent comps, an honest rehab estimate, a conservative ARV, and the <b>spread</b> laid out plainly.</p><p>That means you evaluate a deal in minutes instead of chasing comps all weekend. Whether you flip, <b>BRRRR</b>, or buy and hold, our list is built to match <b>investment properties in {City}</b> to your buy box — and it's completely free, with no contract and no fee to buy. We make our money on the wholesale spread, not on you, and we send every new deal by text and email the moment we lock it up.</p><h3>Deals that actually pencil</h3><p>We keep a tight list of serious investors on purpose: reliable closers earn the best deals first. Cash and hard money get first look because they close fastest, but tell us how you fund and we'll match you to deals you can actually close. <a href="/how-it-works">See exactly how it works</a>, or <a href="/properties">browse discount investment properties for sale in {City} →</a>.</p>`,
        pullQuote: "We'd rather send you one deal you actually fund than flood your inbox with listings that don't pencil.",
      },
      {
        eyebrow: "Investing in {City}",
        heading: "Why {City} keeps producing deals for flippers and landlords.",
        bodyHtml: `<p>Steady rental demand, motivated sellers, and neighborhoods at every price point make {City} a productive market for real estate investors. Whether you're flipping closer in or cash-flowing rentals further out, the spread is there if you know where to look.</p><h3>Flips vs. rentals</h3><p>We send both. <b>Fix-and-flip</b> deals with strong resale comps for investors who want a fast turn, and <b>cash-flowing rental properties in {City}</b> for buy-and-hold investors building a portfolio. Every deal lands with comps, rehab, and ARV so you can run your own return before you commit.</p><h3>First look beats the open market</h3><p>Finding the off-market <b>investment properties</b> that actually hit your numbers is exactly what we do, and the buyers list sees every new wholesale or distressed deal the moment it lands. Tell us your buy box and we'll only send deals that fit. <a href="/properties">Browse discount investment properties for sale →</a>, or <a href="/get-on-the-list">join the investor list — it's free →</a></p>`,
      },
    ],
    types: [
      { title: "Fix-and-flip deals", body: "Off-market homes with strong resale comps and the rehab already estimated.", href: "/properties" },
      { title: "Cash-flow rentals", body: "Single-family and small multifamily that cash-flow from day one.", href: "/properties" },
      { title: "BRRRR-ready properties", body: "Distressed deals that refinance cleanly once rehabbed and rented.", href: "/properties" },
      { title: "Bank-owned & REO", body: "Bank-owned and REO investment properties priced to move.", href: "/properties" },
      { title: "Wholesale & assignment deals", body: "Locked-up contracts we assign to you with the spread already run.", href: "/properties" },
      { title: "Value-add multifamily", body: "Small multifamily in {City} with room to push rents and value.", href: "/properties" },
    ],
    situations: {
      heading: "Where our {City} investment deals come from",
      intro: "We underwrite off-market deals from the situations that produce real spread — then send the ones that pencil straight to the investor list.",
      items: [
        { icon: "📊", title: "Underwritten flips", body: "Comps, rehab estimate, and ARV done before it ever reaches you — verify the spread yourself.", href: "/properties" },
        { icon: "🏘️", title: "Off-market rentals", body: "Cash-flowing single-family and small multifamily from tired landlords selling direct.", href: "/properties" },
        { icon: "📜", title: "Probate & estate sales", body: "Inherited properties from heirs who want a fast, clean close over a retail listing.", href: "/properties" },
        { icon: "🏛️", title: "Pre-foreclosure", body: "Motivated owners who need to move before the auction — frequently the deepest discounts.", href: "/properties" },
        { icon: "🧾", title: "Tax-delinquent", body: "Owners under back-tax pressure, often with vacant properties priced well under market.", href: "/properties" },
        { icon: "🔨", title: "Distressed & value-add", body: "Rough properties and underperforming rentals with clear upside for the right buyer.", href: "/properties" },
      ],
    },
    areas: {
      heading: "Where we find deals",
      intro: "We source off-market investment properties across {City} and nearby — browse by area:",
      singleLine: "We source off-market investment properties throughout {City} and the surrounding area.",
    },
    trustBar: [
      { value: "$0", label: "Free to join" },
      { value: "Numbers run", label: "Repairs & ARV included" },
      { value: "30–50%", label: "Under retail value" },
      { value: "Off-market", label: "Before it hits the market" },
    ],
  },
  rto: {
    label: "Rent-to-own buyers",
    eyebrow: "Rent-to-own homes",
    headline: "Rent-to-own homes in {City} — move in now, buy when you're ready.",
    subhead:
      "Bad credit, self-employed, or just not bank-ready yet? {Brand} matches you with rent-to-own homes so you can settle in today and own it down the road — no bank required to get started.",
    stat: "A real path to owning — even if the bank said no",
    formTitle: "Find your rent-to-own home",
    formSubtitle: "New lease-to-own homes, by text and email.",
    ctaLabel: "Send me homes",
    bannerCta: "Get rent-to-own homes",
    features: [
      { icon: "🔑", title: "Move in now", body: "Get into a home today and lock in your option to buy it later. No waiting years to qualify first." },
      { icon: "🤝", title: "Credit isn't a dealbreaker", body: "Bad credit, thin credit, self-employed — we work with where you are, not just a score." },
      { icon: "🏡", title: "A path to ownership", body: "Part of your rent goes toward the purchase. You're building toward owning, not renting forever." },
    ],
    announcement: "New rent-to-own homes in {City} every week — join free and see them first.",
    howItWorks: [
      { title: "Tell us what you need", body: "Bedrooms, budget, the areas you want. Thirty seconds, and no credit pull to get started." },
      { title: "Get matched homes", body: "We text and email you rent-to-own homes that fit, with the terms in plain English." },
      { title: "Move in, then buy", body: "Pick your home, move in, and work toward owning it on a timeline that fits your life." },
    ],
    faqs: [
      { q: "Can I do this with bad credit?", a: "Often, yes. Rent-to-own is built for buyers who aren't bank-ready yet. We look at the whole picture, not just a number, and help you work toward qualifying." },
      { q: "How does rent-to-own actually work?", a: "You move in and rent the home now with the right to buy it later at a set price. A portion of what you pay can go toward the purchase, so you build toward ownership while you live there." },
      { q: "Do I need a big down payment?", a: "Usually far less than a traditional purchase. We'll walk you through the exact terms on any home before you commit — no surprises." },
      { q: "Is this a scam? How are you different?", a: "Fair question; there are bad actors out there. We put every term in writing, in plain English, and never pressure you. If a home isn't right for you, we'll say so." },
      { q: "What if my credit improves faster than expected?", a: "Even better — you can move toward buying sooner. The goal is to get you owning, not to keep you renting." },
      { q: "How do I stop getting texts?", a: "Reply STOP anytime and you're off the list instantly." },
    ],
    about: {
      headline: "We help families get into a home — and onto the path to owning it.",
      body: "{Brand} works with buyers in {City} who are ready for a home but aren't bank-ready yet. We match you with rent-to-own homes, explain every term in plain English, and help you move toward ownership at a pace that fits your life. No judgment, no pressure — just a real path forward for people the traditional system overlooks.",
      trust: ["Clear terms, in writing", "No credit pull to start", "Real path to ownership"],
    },
    prose: [
      {
        eyebrow: "Why {Brand}",
        heading: "Rent-to-own homes in {City} you can move into now and buy when you're ready.",
        bodyHtml: `<p>If a bank turned you down — or you're just not mortgage-ready yet — that doesn't mean you can't get into a home. {Brand} matches families in {City} with <b>rent-to-own homes</b> and <b>lease-option</b> properties: you move in now, rent while you get mortgage-ready, and lock in your price to buy later. No bank approval to get started, and a real path to ownership instead of paying someone else's mortgage forever.</p><p>Join our list and we'll send <b>rent-to-own homes in {City}</b> by text and email as they come available, with the monthly payment, the move-in amount, and the terms laid out up front. No surprises, no runaround — just homes you can actually qualify for and a clear path to owning them.</p><h3>Built for buyers banks said no to</h3><p>Bruised credit, self-employed income, a recent move, a short time on the job — the things that make banks nervous don't disqualify you here. We work with <b>lease-purchase</b> and <b>rent-to-own</b> buyers every day. <a href="/how-it-works">See how rent-to-own works</a>, or <a href="/properties">browse available rent-to-own homes in {City} →</a>.</p>`,
        pullQuote: "Rent-to-own is the bridge between renting now and owning soon.",
      },
      {
        eyebrow: "Renting to own in {City}",
        heading: "How rent-to-own gets you into a {City} home sooner.",
        bodyHtml: `<p>A <b>rent-to-own home</b> (also called a lease-option or lease-purchase) lets you move into the house now under a rental agreement, with the option to buy it at a price set up front. The deal is simple: you live there, you get your credit and savings where they need to be, and when you're ready you buy.</p><h3>What you get up front</h3><p>Every home we send comes with the monthly payment, the option/move-in amount, and the purchase price spelled out — so you know exactly what it takes to get in and what it takes to own. No guessing, no hidden terms.</p><h3>A real path, not a trap</h3><p>The best rent-to-own deals are the ones where the numbers actually work for you, and the list sees new homes the moment they come up — by text and email. Tell us what you're looking for and your budget, and we'll match you to homes you can realistically move into and buy. <a href="/properties">Browse available rent-to-own homes in {City} →</a>, or <a href="/get-on-the-list">join the rent-to-own list — it's free →</a></p>`,
      },
    ],
    types: [
      { title: "Rent-to-own homes", body: "Move in now, rent while you get ready, and buy at a price locked up front.", href: "/properties" },
      { title: "Lease-option homes", body: "Rent with the option to buy — you choose whether to purchase later.", href: "/properties" },
      { title: "Lease-purchase deals", body: "A clear path to ownership with terms set from day one.", href: "/properties" },
      { title: "Bad-credit-friendly homes", body: "Homes for buyers banks said no to — no mortgage approval to start.", href: "/properties" },
      { title: "Low move-in homes", body: "Get into a home without a 20% down payment hanging over you.", href: "/properties" },
      { title: "Move-in-ready homes", body: "Homes ready for you to move into now while you work toward owning.", href: "/properties" },
    ],
    situations: {
      heading: "Who we help into a {City} home",
      intro: "Rent-to-own exists for buyers who are ready to own but aren't bank-ready yet. If any of these is you, the list is built for you.",
      items: [
        { icon: "📉", title: "Bruised or rebuilding credit", body: "Move in now and use the rental period to get your score where lenders want it.", href: "/properties" },
        { icon: "💼", title: "Self-employed income", body: "Hard to document on a mortgage app — but no problem on a rent-to-own.", href: "/properties" },
        { icon: "💰", title: "Saving the down payment", body: "Get into a home now while you build the savings to buy it later.", href: "/properties" },
        { icon: "🆕", title: "New job or recent move", body: "Banks want time on the job; we don't. Get settled now.", href: "/properties" },
        { icon: "🏠", title: "Tired of renting", body: "Stop paying a landlord's mortgage — put those payments toward your own home.", href: "/properties" },
        { icon: "📝", title: "Past bankruptcy or foreclosure", body: "A rough patch doesn't disqualify you from a path back to ownership.", href: "/properties" },
      ],
    },
    areas: {
      heading: "Where we have homes",
      intro: "We have rent-to-own homes across {City} and nearby — browse by area:",
      singleLine: "We work with rent-to-own homes throughout {City} and the surrounding area.",
    },
    trustBar: [
      { value: "$0", label: "No application fee" },
      { value: "Move-in ready", label: "Homes available now" },
      { value: "Credit-flexible", label: "Build toward owning" },
      { value: "Rent-to-own", label: "Buy when you're ready" },
    ],
  },
  owner: {
    label: "Owner-finance buyers",
    eyebrow: "Owner-financed homes",
    headline: "Owner-financed homes in {City} — buy direct from the owner, skip the bank.",
    subhead:
      "{Brand} matches you with homes you can buy on owner financing — flexible terms, faster closings, and no bank underwriting standing between you and the keys.",
    stat: "Buy on terms — no bank required",
    formTitle: "Find owner-financed homes",
    formSubtitle: "New seller-financed homes, by text and email.",
    ctaLabel: "Send me homes",
    bannerCta: "Get owner-financed homes",
    features: [
      { icon: "🏦", title: "Skip the bank", body: "Buy directly from the owner on agreed terms. No mortgage application, no underwriting maze." },
      { icon: "⚡", title: "Close faster", body: "Without a bank in the middle, owner-financed deals can close in a fraction of the time." },
      { icon: "🤝", title: "Flexible terms", body: "Down payment, rate, and length are negotiated between you and the owner — room to fit your situation." },
    ],
    announcement: "New owner-financed homes in {City} every week — join free to see them first.",
    howItWorks: [
      { title: "Tell us what you want", body: "Budget, the down payment you can put down, and the areas you like. Thirty seconds." },
      { title: "Get matched homes", body: "We text and email you owner-financed homes that fit, with the terms spelled out clearly." },
      { title: "Agree terms and close", body: "Negotiate directly with the owner, sign, and get your keys — no bank approval needed." },
    ],
    faqs: [
      { q: "How is owner financing different from a normal mortgage?", a: "Instead of borrowing from a bank, you buy directly from the owner and pay them over time on agreed terms. No bank application, no underwriting — just you and the seller." },
      { q: "Do I need perfect credit?", a: "Usually not. Owner financing is far more flexible than a bank loan; the terms are set between you and the owner, so your situation matters more than a single score." },
      { q: "How big a down payment do I need?", a: "It varies by home and owner; some are flexible. We'll show you the exact terms on any property before you commit." },
      { q: "Is owner financing legit and safe?", a: "Yes — it's a long-established way to buy. Every deal is documented properly, and we make sure the terms are clear and in writing before you sign." },
      { q: "Can I refinance into a bank loan later?", a: "Often, yes. Many buyers use owner financing to get into the home now and refinance once they qualify with a bank." },
      { q: "How do I stop the texts?", a: "Reply STOP anytime to opt out instantly." },
    ],
    about: {
      headline: "Buy a home on your terms — straight from the owner.",
      body: "{Brand} matches buyers in {City} with owner-financed homes — properties you can purchase directly from the seller, without a bank in the middle. We explain every term clearly, keep the process honest, and help buyers who don't fit a bank's box get into a home they own. Flexible terms, faster closings, real ownership.",
      trust: ["Clear terms, in writing", "No bank underwriting", "Faster closings"],
    },
    prose: [
      {
        eyebrow: "Why {Brand}",
        heading: "Owner-financed homes in {City} — buy direct from the seller, no bank.",
        bodyHtml: `<p>Bank financing isn't the only way to buy a house. {Brand} connects buyers in {City} with <b>owner-financed homes</b> — properties where the seller carries the financing, so you buy directly from them with a down payment and monthly payments, no mortgage lender involved. For self-employed buyers, investors maxed out on conventional loans, and anyone the banks make jump through hoops, <b>seller financing</b> is often the fastest, simplest way into a home.</p><p>Join our list and we'll send <b>owner-financed homes in {City}</b> by text and email as they come available, each with the down payment, monthly payment, interest rate, and terms laid out up front. You see the whole deal before you ever talk to anyone — no surprises, no bank underwriting, no waiting weeks for an approval that may never come.</p><h3>Why buyers choose owner financing</h3><p>Flexible terms you can actually negotiate, a faster close than any bank can offer, and qualification based on the deal — not a credit committee. <a href="/how-it-works">See how owner financing works</a>, or <a href="/properties">browse available owner-financed homes in {City} →</a>.</p>`,
        pullQuote: "Owner financing puts the deal between you and the seller — not a bank.",
      },
      {
        eyebrow: "Owner financing in {City}",
        heading: "How owner financing gets you into a {City} home without a bank.",
        bodyHtml: `<p>With an <b>owner-financed</b> (or <b>seller-financed</b>) home, the seller acts as the bank. You agree on a price, a down payment, an interest rate, and a monthly payment — and you start building equity from day one, without a mortgage lender in the middle.</p><h3>What you get up front</h3><p>Every owner-finance deal we send comes with the down payment, the monthly payment, and the terms spelled out, so you know exactly what it takes to get in and what you'll pay each month. The terms are negotiable in a way bank loans never are.</p><h3>Built for buyers banks overlook</h3><p>Self-employed, 1099, recently relocated, or just done with bank red tape — owner financing is built for you, and the list sees new homes the moment they come up by text and email. Tell us your budget and down payment, and we'll match you to homes you can buy on terms that work. <a href="/properties">Browse available owner-financed homes in {City} →</a>, or <a href="/get-on-the-list">join the owner-finance list — it's free →</a></p>`,
      },
    ],
    types: [
      { title: "Owner-financed homes", body: "Buy direct from the seller with a down payment and monthly payments — no bank.", href: "/properties" },
      { title: "Seller-financed houses", body: "The seller carries the note; you build equity from day one.", href: "/properties" },
      { title: "Low-down-payment homes", body: "Get in without the 20% a conventional loan demands.", href: "/properties" },
      { title: "Self-employed friendly", body: "Qualification based on the deal, not two years of tax returns.", href: "/properties" },
      { title: "No-bank deals", body: "Skip the lender, the underwriting, and the weeks of waiting.", href: "/properties" },
      { title: "Flexible-terms homes", body: "Down payment, rate, and timeline you can actually negotiate.", href: "/properties" },
    ],
    situations: {
      heading: "Who owner financing is built for in {City}",
      intro: "If a bank makes buying harder than it should be, owner financing is often the cleaner path. These buyers use it every day.",
      items: [
        { icon: "💼", title: "Self-employed & 1099", body: "Income that's hard to document for a mortgage is no obstacle here.", href: "/properties" },
        { icon: "🏦", title: "Maxed-out investors", body: "Already at your conventional-loan limit? Owner financing keeps you buying.", href: "/properties" },
        { icon: "💰", title: "Want lower down", body: "Negotiate a down payment that fits instead of a fixed 20%.", href: "/properties" },
        { icon: "⏱️", title: "Need to close fast", body: "No bank underwriting means a close measured in days, not weeks.", href: "/properties" },
        { icon: "📉", title: "Credit banks won't touch", body: "Qualification based on the deal and the down payment, not a score.", href: "/properties" },
        { icon: "🤝", title: "Want negotiable terms", body: "Price, rate, and timeline are between you and the seller.", href: "/properties" },
      ],
    },
    areas: {
      heading: "Where we have homes",
      intro: "We have owner-financed homes across {City} and nearby — browse by area:",
      singleLine: "We work with owner-financed homes throughout {City} and the surrounding area.",
    },
    trustBar: [
      { value: "$0", label: "Free to join" },
      { value: "No bank", label: "Buy direct from the owner" },
      { value: "Flexible terms", label: "Down-payment options" },
      { value: "Owner-financed", label: "Homes you won't find listed" },
    ],
  },
  creative: {
    label: "Creative-finance buyers",
    eyebrow: "Creative-finance deals",
    headline: "Creative-finance deals in {City} — control properties without all-cash or a bank.",
    subhead:
      "{Brand} sends off-market deals built for creative structures — subject-to, seller finance, wraps, and lease options — so you can acquire with little money down and terms that actually work.",
    stat: "Deals structured to close — low money down",
    formTitle: "Get creative-finance deals",
    formSubtitle: "Off-market, structurable deals — by text and email.",
    ctaLabel: "Send me deals",
    bannerCta: "Join the deals list",
    features: [
      { icon: "🧩", title: "Deals you can structure", body: "Motivated sellers open to terms: subject-to, seller finance, wraps, lease options. The kind of deal a creative buyer can actually do." },
      { icon: "💡", title: "Low money down", body: "Acquire and control properties without bringing all-cash or qualifying for a bank loan." },
      { icon: "🥇", title: "First look at terms deals", body: "We surface sellers open to creative structures before they ever list, and send them to you first." },
    ],
    announcement: "New creative-finance deals in {City} weekly — sent to our buyers first.",
    howItWorks: [
      { title: "Tell us how you structure", body: "Subject-to, seller finance, lease option, wrap — and your buy box. Thirty seconds." },
      { title: "Get matched deals", body: "We text and email you off-market properties with sellers open to terms, the situation laid out." },
      { title: "Structure and close", body: "Reply to claim it; we connect you with the seller and you build the deal that works." },
    ],
    faqs: [
      { q: "What kind of creative deals do you send?", a: "Off-market properties where the seller is open to terms — subject-to, seller financing, lease options, and wraps. We tell you the seller's situation so you can structure it." },
      { q: "Do sellers actually agree to these terms?", a: "The ones we send do. We pre-qualify for motivation and openness to terms before a deal goes out, so you're not cold-pitching creative structures." },
      { q: "Do I need cash or credit?", a: "Far less than a traditional purchase. Creative deals are built to acquire with little money down and without bank qualifying — that's the whole point." },
      { q: "Is creative financing legal and clean?", a: "Yes, when it's documented right. We deal in real, properly-papered transactions and tell you the seller's exact situation up front." },
      { q: "Is there a fee to join?", a: "No. The list is free, no contract. We make our money on the deal spread, not on you." },
      { q: "How do I stop the texts?", a: "Reply STOP anytime to opt out instantly." },
    ],
    about: {
      headline: "Off-market deals built for creative buyers.",
      body: "{Brand} finds motivated sellers across {City} who are open to terms — subject-to, seller financing, lease options, and wraps — and sends those deals to a tight list of creative buyers first. We tell you the seller's real situation so you can structure a deal that closes with little money down. No bank, no bidding war, just deals you can actually do.",
      trust: ["Sellers pre-qualified for terms", "Low money down", "Built for creative buyers"],
    },
    prose: [
      {
        eyebrow: "Why {Brand}",
        heading: "Creative-finance real estate deals in {City} — structured to close without a bank.",
        bodyHtml: `<p>The best deals often aren't bankable in the traditional sense — and that's exactly where the opportunity is. {Brand} sources off-market properties in {City} built for <b>creative financing</b>: <b>subject-to</b>, <b>seller carry</b>, and <b>lease options</b>. Instead of a new bank loan, you take over existing financing or buy on terms the seller carries — which means lower entry costs, faster closes, and deals other buyers can't touch.</p><p>Join our list and we'll send <b>creative-finance deals in {City}</b> by text and email as we lock them up, each with the structure, the existing terms, and your monthly numbers laid out up front. You see exactly how the deal is built before you commit — no guesswork, no scrambling to figure out the financing after the fact.</p><h3>Built for buyers who know terms</h3><p>If you understand <b>subject-to</b> and <b>seller financing</b>, you already know these deals close faster and cheaper than anything a bank touches. <a href="/how-it-works">See how it works</a>, or <a href="/properties">browse available creative-finance deals in {City} →</a>.</p>`,
        pullQuote: "The deal that can't get a bank loan is often the best deal on the table.",
      },
      {
        eyebrow: "Creative financing in {City}",
        heading: "How creative-finance deals work in {City}.",
        bodyHtml: `<p><b>Creative financing</b> covers any way to buy a property without a new conventional mortgage. The three most common: <b>subject-to</b> (you take over the seller's existing loan), <b>seller carry</b> (the seller finances the sale), and <b>lease options</b> (you control the property with the right to buy later).</p><h3>Why the structure matters</h3><p>Each structure changes your entry cost, your monthly obligation, and your exit. We lay all of it out on every deal — the existing loan, the terms the seller will carry, the monthly PITI — so you can underwrite the structure, not just the property.</p><h3>Deals built for terms buyers</h3><p>We lock these up off-market and the list sees each one the moment it lands, by text and email. Tell us the structures you work with — subject-to, seller carry, lease option — and we'll send the ones that fit how you buy. <a href="/properties">Browse available creative-finance deals in {City} →</a>, or <a href="/get-on-the-list">join the deals list — it's free →</a></p>`,
      },
    ],
    types: [
      { title: "Subject-to deals", body: "Take over the seller's existing financing and keep the low rate in place.", href: "/properties" },
      { title: "Seller-carry deals", body: "The seller finances the sale on terms you negotiate together.", href: "/properties" },
      { title: "Lease options", body: "Control the property now with the right to buy it later.", href: "/properties" },
      { title: "Low-entry deals", body: "Get in with far less cash than a conventional purchase requires.", href: "/properties" },
      { title: "No-new-loan deals", body: "Skip the bank entirely with existing or seller-carried financing.", href: "/properties" },
      { title: "Terms-flexible properties", body: "Structures you can shape to fit your strategy and exit.", href: "/properties" },
    ],
    situations: {
      heading: "Deal structures we send in {City}",
      intro: "Every creative deal we lock up comes with the structure spelled out so you can underwrite the terms, not just the property.",
      items: [
        { icon: "🔑", title: "Subject-to", body: "Take title and take over the existing loan — often at a rate you'll never get today.", href: "/properties" },
        { icon: "🤝", title: "Seller carry", body: "The seller finances the deal; you negotiate the down, rate, and term.", href: "/properties" },
        { icon: "📄", title: "Lease option", body: "Control the property and lock the purchase price while you decide.", href: "/properties" },
        { icon: "💵", title: "Low cash to close", body: "Creative structures keep your entry costs far below a conventional buy.", href: "/properties" },
        { icon: "⚡", title: "Fast close, no bank", body: "No underwriting means you close on the deal in days.", href: "/properties" },
        { icon: "📊", title: "Numbers laid out", body: "Existing terms and monthly PITI on every deal, before you commit.", href: "/properties" },
      ],
    },
    areas: {
      heading: "Where we find deals",
      intro: "We find creative-finance deals across {City} and nearby — browse by area:",
      singleLine: "We find creative-finance deals throughout {City} and the surrounding area.",
    },
    trustBar: [
      { value: "$0", label: "Free to join" },
      { value: "No bank", label: "Control without a loan" },
      { value: "Low down", label: "Subject-to & seller terms" },
      { value: "Off-market", label: "Creative deals sent first" },
    ],
  },
  land: {
    label: "Land buyers",
    eyebrow: "Off-market land deals",
    headline: "Off-market land and acreage in {City} — priced below market, sent first.",
    subhead:
      "{Brand} sources off-market lots and acreage and sends them to our land buyers list before they hit the market — buildable parcels, recreational tracts, and investment land with real upside.",
    stat: "Off-market land, under market",
    formTitle: "Get land deals sent to you",
    formSubtitle: "New off-market lots and acreage, by text and email.",
    ctaLabel: "Send me land",
    bannerCta: "Join the land list",
    features: [
      { icon: "🌳", title: "Off-market parcels", body: "Lots and acreage direct from motivated owners, never on the open market, priced to move." },
      { icon: "📐", title: "The details up front", body: "Acreage, access, zoning, and utilities laid out so you know what you're buying before you drive out." },
      { icon: "🥇", title: "First look", body: "Our land list sees new parcels before they're listed. The good ones go fast." },
    ],
    announcement: "New off-market land in {City} every week — land list gets it first.",
    howItWorks: [
      { title: "Tell us what you're after", body: "Acreage, budget, area, and use: build, invest, or recreation. Thirty seconds." },
      { title: "Get matched parcels", body: "We text and email you off-market land that fits, with acreage, access, and zoning spelled out." },
      { title: "Lock it up", body: "Reply to claim it and we hand you a clean contract; close fast." },
    ],
    faqs: [
      { q: "What kind of land do you send?", a: "Buildable lots, larger acreage, recreational and hunting tracts, and investment land — all off-market and priced below retail." },
      { q: "Do you include zoning and access info?", a: "Yes. Every parcel comes with acreage, access, and what we know about zoning and utilities so you can evaluate it before driving out." },
      { q: "Is the land buildable?", a: "Some is build-ready, some is raw or recreational. We tell you which on every parcel, so there are no surprises." },
      { q: "Do you offer owner financing on land?", a: "On some parcels, yes. Where an owner is open to terms, we'll spell them out clearly." },
      { q: "Is there a fee to join?", a: "No. The list is free, no contract. We make our money on the deal spread, not on you." },
      { q: "How do I stop the texts?", a: "Reply STOP anytime to opt out instantly." },
    ],
    about: {
      headline: "Off-market land, priced to move — sent to buyers who act.",
      body: "{Brand} sources off-market lots and acreage across {City} and the surrounding area — buildable parcels, recreational tracts, and investment land — and sends them to our land buyers list before they're ever listed. We give you acreage, access, and zoning up front so you can move with confidence. No retail markup, no bidding war.",
      trust: ["Off-market parcels", "Details up front", "We close on time"],
    },
    prose: [
      {
        eyebrow: "Why {Brand}",
        heading: "Off-market land and acreage in {City} — priced below market, sent first.",
        bodyHtml: `<p>Good land deals don't sit on the MLS. By the time a parcel is listed and marketed, the price reflects it. {Brand} works the off-market side: we find <b>vacant land</b>, <b>acreage</b>, and <b>buildable lots</b> in and around {City} directly from owners who need to sell — back taxes, inherited parcels, tired holders — and send them to our land buyers list before they're ever publicly listed.</p><p>Join our list and we'll send <b>off-market land in {City}</b> by text and email as we lock it up, each with the acreage, zoning, access, utilities, and price laid out up front. Whether you're buying to build, to hold, or to flip, you get the details that actually matter for land — not a vague listing — so you can move fast on the parcels worth moving on.</p><h3>Built for land buyers and developers</h3><p>Infill lots, rural acreage, recreational tracts, and development parcels — we source the kind of <b>land for sale in {City}</b> that has real spread because we buy it right. <a href="/how-it-works">See how it works</a>, or <a href="/properties">browse available land and lots in {City} →</a>.</p>`,
        pullQuote: "The land worth buying is gone before it's ever listed — unless you're on the list.",
      },
      {
        eyebrow: "Buying land in {City}",
        heading: "What to know about buying off-market land in {City}.",
        bodyHtml: `<p>Land is its own game. Zoning, access, utilities, flood, and buildability matter far more than they do on a house — and the difference between a great lot and a useless one comes down to those details.</p><h3>The details we put up front</h3><p>Every parcel we send includes acreage, zoning/use, road access, and whether utilities are at the street — the things that decide whether a lot is buildable and what it's worth. No driving out to discover a dead deal.</p><h3>From infill lots to rural acreage</h3><p>We source <b>buildable lots</b> for builders, <b>acreage</b> for buyers who want room, and discounted parcels for investors who flip land, and the list sees each new parcel the moment we lock it up by text and email. Tell us what you're after — lot size, use, and budget — and we'll send parcels that fit. <a href="/properties">Browse available land and lots in {City} →</a>, or <a href="/get-on-the-list">join the land buyers list — it's free →</a></p>`,
      },
    ],
    types: [
      { title: "Buildable lots", body: "Infill and ready-to-build lots with access and utilities sorted.", href: "/properties" },
      { title: "Acreage & rural land", body: "Larger tracts for buyers who want room to build or hold.", href: "/properties" },
      { title: "Off-market parcels", body: "Land direct from motivated owners, never listed publicly.", href: "/properties" },
      { title: "Recreational land", body: "Hunting, camping, and getaway tracts priced below market.", href: "/properties" },
      { title: "Development parcels", body: "Larger pieces with upside for builders and developers.", href: "/properties" },
      { title: "Below-market lots", body: "Discounted lots we lock up from tax-delinquent and inherited owners.", href: "/properties" },
    ],
    situations: {
      heading: "Where our {City} land deals come from",
      intro: "Most off-market land comes from owners who'd rather take a fast, clean offer than wait out a listing. These are the situations that produce the best parcels.",
      items: [
        { icon: "🧾", title: "Tax-delinquent parcels", body: "Owners under back-tax pressure on land they no longer want to hold.", href: "/properties" },
        { icon: "📜", title: "Inherited land", body: "Heirs who inherited acreage they have no plans for and want to cash out.", href: "/properties" },
        { icon: "🗺️", title: "Out-of-state owners", body: "Absentee owners holding land they've never used and want off the books.", href: "/properties" },
        { icon: "🏗️", title: "Buildable infill lots", body: "City and suburban lots ready for a build, with access and utilities.", href: "/properties" },
        { icon: "🌲", title: "Rural acreage", body: "Larger tracts for building, holding, or recreation, priced to move.", href: "/properties" },
        { icon: "💵", title: "Below-market flips", body: "Discounted parcels with spread for buyers who flip land.", href: "/properties" },
      ],
    },
    areas: {
      heading: "Where we find land",
      intro: "We source off-market land across {City} and nearby — browse by area:",
      singleLine: "We source off-market land throughout {City} and the surrounding area.",
    },
    trustBar: [
      { value: "$0", label: "Free to join" },
      { value: "<24h", label: "New parcels to your inbox" },
      { value: "Below market", label: "Priced to move" },
      { value: "Off-market", label: "Land you won't find listed" },
    ],
  },
  commercial: {
    label: "Commercial buyers",
    eyebrow: "Off-market commercial deals",
    headline: "Off-market commercial and multifamily in {City} — with upside, sent first.",
    subhead:
      "{Brand} sources off-market commercial and multi-family deals — apartments, retail, office, and value-add plays — and sends them to our commercial buyers before they ever reach a broker's inbox.",
    stat: "Off-market commercial, with real upside",
    formTitle: "Get commercial deals sent to you",
    formSubtitle: "Off-market commercial and multifamily, by text and email.",
    ctaLabel: "Send me deals",
    bannerCta: "Join the commercial list",
    features: [
      { icon: "🏢", title: "Off-market & value-add", body: "Apartments, retail, office, and mixed-use direct from owners, including value-add plays the market hasn't seen." },
      { icon: "📊", title: "The numbers up front", body: "Units, rents, occupancy, and the value-add thesis laid out so you can screen it fast." },
      { icon: "🥇", title: "Before the broker", body: "Our list sees off-market commercial deals before they're packaged and shopped to the market." },
    ],
    announcement: "New off-market commercial and multifamily in {City} — buyers list gets it first.",
    howItWorks: [
      { title: "Tell us your criteria", body: "Asset type, size, market, and return targets. Thirty seconds." },
      { title: "Get matched deals", body: "We send off-market commercial and multi-family that fits, with the key numbers up front." },
      { title: "Lock it up", body: "Reply to move on it; we connect you to the deal and you close on your terms." },
    ],
    faqs: [
      { q: "What asset types do you send?", a: "Multi-family, retail, office, industrial, and mixed-use, with a focus on off-market and value-add opportunities." },
      { q: "Do you provide financials?", a: "We send the key numbers we have — units, rents, occupancy, and the value-add thesis — so you can screen fast and request the full package." },
      { q: "How off-market are these really?", a: "We source direct from owners before deals are packaged and shopped, so our buyers see them ahead of the broader market." },
      { q: "What deal sizes do you cover?", a: "From small multi-family up through larger commercial. Tell us your range and we'll match it." },
      { q: "Is there a fee to join?", a: "No. The list is free, no contract. We're compensated on the deal, not on you." },
      { q: "How do I stop the alerts?", a: "Reply STOP anytime to opt out instantly." },
    ],
    about: {
      headline: "Off-market commercial deals — sent to buyers who can close them.",
      body: "{Brand} sources off-market commercial and multi-family deals across {City} and the surrounding area — apartments, retail, office, and value-add plays — and sends them to a focused list of commercial buyers before they're ever shopped to the market. We give you the key numbers up front so you can screen quickly and act on the ones that fit.",
      trust: ["Off-market, pre-broker", "Numbers up front", "Built for serious buyers"],
    },
    prose: [
      {
        eyebrow: "Why {Brand}",
        heading: "Off-market commercial and multifamily in {City} — with upside, sent first.",
        bodyHtml: `<p>The commercial deals worth chasing rarely reach a broker's listing. {Brand} sources off-market <b>commercial real estate</b> and <b>multifamily</b> in {City} — apartments, retail, office, and mixed-use — direct from owners ready to sell, and sends them to our commercial buyers list before they ever hit the open market or a broker's inbox.</p><p>Join our list and we'll send <b>off-market commercial and multifamily deals in {City}</b> by text and email as we lock them up, each with the units, building size, current rents, <b>cap rate</b>, and <b>value-add</b> story laid out up front. You get enough to underwrite the deal on first look — not a teaser that makes you sign an NDA just to see the numbers.</p><h3>Built for buyers who close</h3><p>Whether you're acquiring stabilized cash-flow or hunting <b>value-add multifamily</b> with room to push rents, we send the <b>investment property</b> deals that actually pencil. <a href="/how-it-works">See how it works</a>, or <a href="/properties">browse available commercial deals in {City} →</a>.</p>`,
        pullQuote: "We'd rather send you one deal that pencils than ten that waste your time.",
      },
      {
        eyebrow: "Investing in {City}",
        heading: "Why commercial and multifamily in {City} still has room to run.",
        bodyHtml: `<p>Steady demand, rent growth in the right submarkets, and owners ready to trade out make {City} a productive market for commercial and multifamily buyers — if you can find the off-market deals before they're shopped around.</p><h3>Stabilized vs. value-add</h3><p>We send both: stabilized assets for buyers who want cash-flow on day one, and <b>value-add</b> deals — under-rented units, deferred maintenance, mismanaged buildings — for buyers who want to force appreciation. Every deal lands with the rent roll basics and a cap rate so you can decide fast.</p><h3>First look beats the open market</h3><p>We lock these up off-market and the list sees each one the moment it lands, by text and email. Tell us your buy box — asset type, size, and return targets — and we'll send the deals that fit. <a href="/properties">Browse available commercial and multifamily deals in {City} →</a>, or <a href="/get-on-the-list">join the commercial buyers list — it's free →</a></p>`,
      },
    ],
    types: [
      { title: "Multifamily & apartments", body: "Off-market apartment buildings and small multifamily with upside.", href: "/properties" },
      { title: "Retail & strip centers", body: "Off-market retail with in-place income and room to improve.", href: "/properties" },
      { title: "Office & flex", body: "Office and flex space priced below replacement cost.", href: "/properties" },
      { title: "Mixed-use", body: "Mixed-use buildings combining income streams in one asset.", href: "/properties" },
      { title: "Value-add deals", body: "Under-rented, mismanaged, or distressed assets with forced-appreciation upside.", href: "/properties" },
      { title: "Stabilized cash-flow", body: "Performing assets for buyers who want day-one income.", href: "/properties" },
    ],
    situations: {
      heading: "Where our {City} commercial deals come from",
      intro: "Off-market commercial comes from owners ready to trade out quietly. These are the situations that produce real upside.",
      items: [
        { icon: "🏢", title: "Tired owners", body: "Long-time holders ready to sell and move on without a public listing.", href: "/properties" },
        { icon: "📉", title: "Under-rented buildings", body: "Rents below market with clear room to push value through management.", href: "/properties" },
        { icon: "🛠️", title: "Deferred maintenance", body: "Assets that scare retail buyers but pencil for a value-add operator.", href: "/properties" },
        { icon: "🧾", title: "Distressed & note sales", body: "Owners under financial pressure who need a fast, certain close.", href: "/properties" },
        { icon: "📜", title: "Estate & partnership exits", body: "Inherited assets and partner buyouts that need to sell cleanly.", href: "/properties" },
        { icon: "📊", title: "Stabilized trades", body: "Performing buildings traded off-market for buyers wanting day-one cash-flow.", href: "/properties" },
      ],
    },
    areas: {
      heading: "Where we find deals",
      intro: "We source off-market commercial across {City} and nearby — browse by area:",
      singleLine: "We source off-market commercial deals throughout {City} and the surrounding area.",
    },
    trustBar: [
      { value: "$0", label: "Free to join" },
      { value: "Real numbers", label: "Rent rolls & financials" },
      { value: "Value-add", label: "Upside on every deal" },
      { value: "Off-market", label: "Before brokers list it" },
    ],
  },
  agent: {
    label: "Agents & realtors",
    eyebrow: "Off-market inventory for agents",
    headline: "Off-market and pocket listings in {City} — inventory to bring your buyers.",
    subhead:
      "{Brand} gives agents first access to off-market and pocket listings, so you can show your buyers properties no one else has — and win more clients and closings.",
    stat: "Off-market inventory to serve your clients",
    formTitle: "Get off-market inventory",
    formSubtitle: "New pocket listings, by text and email.",
    ctaLabel: "Send me listings",
    bannerCta: "Join the agent list",
    features: [
      { icon: "🗝️", title: "Inventory no one else has", body: "Off-market and pocket listings you can bring to your buyers when the MLS is dry." },
      { icon: "🤝", title: "Your client stays yours", body: "We feed you the inventory; you keep your buyer and your commission. We work the deal side." },
      { icon: "🥇", title: "First access", body: "Agents on our list see new off-market properties before they're ever listed or shopped." },
    ],
    announcement: "New off-market and pocket listings in {City} weekly — agents get first access.",
    howItWorks: [
      { title: "Tell us your buyers' boxes", body: "Areas, price, property type your clients want. Thirty seconds." },
      { title: "Get matched inventory", body: "We text and email you off-market and pocket listings that fit your buyers." },
      { title: "Bring your buyer", body: "Show it, write it up, and close: your client, your commission." },
    ],
    faqs: [
      { q: "Does this cut into my commission?", a: "No. You keep your buyer and your side of the deal. We make our money on the deal we control, not on your commission." },
      { q: "What kind of inventory is this?", a: "Off-market and pocket listings: distressed, motivated-seller, and wholesale properties that aren't on the MLS." },
      { q: "How do I show these to my clients?", a: "We give you the details to bring to your buyer; you handle the relationship and the closing as you normally would." },
      { q: "Is the inventory real and available?", a: "Yes. We control or represent the properties we send, so it's real inventory you can actually transact on." },
      { q: "Is there a cost to join?", a: "No. The list is free, no contract. We're compensated on the deal side, never on you." },
      { q: "How do I stop the texts?", a: "Reply STOP anytime to opt out instantly." },
    ],
    about: {
      headline: "Off-market inventory for agents who want an edge.",
      body: "{Brand} gives agents and realtors across {City} first access to off-market and pocket listings — distressed, motivated-seller, and wholesale properties that never hit the MLS. You bring the inventory to your buyers, keep your client and your commission, and win more business in a tight market. We handle the deal side; you look like the agent who always has something.",
      trust: ["Your client, your commission", "Real, transactable inventory", "First access"],
    },
    prose: [
      {
        eyebrow: "Why {Brand}",
        heading: "Off-market and pocket listings in {City} — for agents with ready buyers.",
        bodyHtml: `<p>Your buyers are tired of losing every bidding war on the MLS. {Brand} gives agents in {City} access to <b>off-market</b> and <b>pocket listings</b> — properties that aren't on the open market yet — so you can bring your buyers something nobody else can show them. Less competition, more spread, and a reason for buyers to stick with you.</p><p>Join our list and we'll send <b>off-market and pocket listings in {City}</b> by text and email as they come available, each with the details and price laid out up front. Show your buyers homes before they're public, write cleaner offers with less competition, and close more of the deals you're already working.</p><h3>Built for buyer's agents</h3><p>Whether your client wants a primary home or an investment property, off-market inventory is the edge that keeps buyers loyal. <a href="/how-it-works">See how it works</a>, or <a href="/properties">browse available off-market listings in {City} →</a>.</p>`,
        pullQuote: "The agent who can show off-market inventory keeps the buyer.",
      },
      {
        eyebrow: "Working {City} off-market",
        heading: "Why off-market inventory wins buyers in {City}.",
        bodyHtml: `<p>On the open market, your buyer is one of ten offers and the price is already bid up. Off-market is the opposite: fewer eyes on the property, more room to negotiate, and a home your buyer couldn't have found on Zillow.</p><h3>What you get</h3><p>We send <b>pocket listings</b>, coming-soon homes, and off-market deals with the details and price up front, so you can match them to the buyers in your pipeline and move fast. It's free to join, and you keep your client — we're sourcing inventory, not your relationship.</p><h3>Inventory that keeps buyers loyal</h3><p>New off-market homes go to the list first, by text and email, the moment they come up. Tell us what your buyers are after — price range, area, and type — and we'll send the off-market homes that fit. <a href="/properties">Browse available off-market listings in {City} →</a>, or <a href="/get-on-the-list">join the agent list — it's free →</a></p>`,
      },
    ],
    types: [
      { title: "Pocket listings", body: "Off-market homes you can show buyers before anyone else.", href: "/properties" },
      { title: "Coming-soon homes", body: "Properties about to list — get your buyers in first.", href: "/properties" },
      { title: "Off-market deals", body: "Homes never publicly listed, with less competition and more room.", href: "/properties" },
      { title: "Investment properties", body: "Off-market deals for your investor clients building portfolios.", href: "/properties" },
      { title: "Below-market homes", body: "Discounted inventory your buyers won't find on the MLS.", href: "/properties" },
      { title: "Exclusive inventory", body: "Properties we source direct, available to agents on the list.", href: "/properties" },
    ],
    situations: {
      heading: "Off-market inventory we send agents in {City}",
      intro: "We source the kind of inventory that gives your buyers an edge and keeps them loyal to you.",
      items: [
        { icon: "🔑", title: "Pocket listings", body: "Homes held off the MLS that you can show before they're public.", href: "/properties" },
        { icon: "⏳", title: "Coming-soon homes", body: "Properties about to list — get your buyer in before the crowd.", href: "/properties" },
        { icon: "💼", title: "Investor inventory", body: "Off-market deals for your investor clients' buy boxes.", href: "/properties" },
        { icon: "🏠", title: "Off-market resale", body: "Owner-direct homes your retail buyers won't find online.", href: "/properties" },
        { icon: "💵", title: "Below-market deals", body: "Discounted properties that help your buyer win without overpaying.", href: "/properties" },
        { icon: "🤝", title: "You keep the client", body: "We source the inventory; the relationship stays yours.", href: "/properties" },
      ],
    },
    areas: {
      heading: "Where we have inventory",
      intro: "We source off-market inventory across {City} and nearby — browse by area:",
      singleLine: "We source off-market inventory throughout {City} and the surrounding area.",
    },
    trustBar: [
      { value: "$0", label: "Free to join" },
      { value: "Off-market", label: "Pocket & unlisted inventory" },
      { value: "For your buyers", label: "Bring them deals first" },
      { value: "<24h", label: "New inventory to your inbox" },
    ],
  },
}

export function getPersona(id: SitePersona): PersonaContent {
  return PERSONAS[id] || PERSONAS.cash
}
