"use client";

import { useEffect, useRef, useState } from "react";

type GreetingSource = "polly" | "recorded" | null;
interface VoiceOption { id: string; label: string; engine: string }
interface Props { scopeId: string; currentUrl: string | null; currentSource: GreetingSource; voices: VoiceOption[]; onSaved: (url: string, source: "polly" | "recorded") => void; onRemoved: () => void }

export default function VoicemailGreetingEditor({ scopeId, currentUrl, currentSource, voices, onSaved, onRemoved }: Props) {
  const [tab, setTab] = useState<"ai" | "record">("ai"); const [text, setText] = useState("Hi, you've reached our acquisitions team. Please leave your name, number, and property address, and we'll call you back as soon as possible.");
  const [voiceId, setVoiceId] = useState(voices[0]?.id ?? "Danielle"); const [previewUrl, setPreviewUrl] = useState<string | null>(null); const [previewSource, setPreviewSource] = useState<"polly" | "recorded" | null>(null);
  const [status, setStatus] = useState(""); const [busy, setBusy] = useState(false); const [recordingUrl, setRecordingUrl] = useState<string | null>(null); const [recordingBlob, setRecordingBlob] = useState<Blob | null>(null);
  const mediaRecorderRef = useRef<MediaRecorder | null>(null); const streamRef = useRef<MediaStream | null>(null);
  useEffect(() => () => { if (streamRef.current) streamRef.current.getTracks().forEach((t) => t.stop()); if (recordingUrl) URL.revokeObjectURL(recordingUrl); }, [recordingUrl]);

  const gen = async (body: BodyInit, headers?: Record<string, string>) => { const res = await fetch("/api/settings/phone-system/generate", { method: "POST", body, headers }); return res.json().then((d) => ({ d, ok: res.ok })); };
  const save = async (payload: Record<string, unknown>) => { const res = await fetch("/api/settings/phone-system", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); return res.json().then((d) => ({ d, ok: res.ok })); };

  return <div className="space-y-4">
    {currentUrl && <div className="rounded-md border p-3"><p className="text-sm font-medium">Current greeting <span className="ml-2 rounded bg-[#ECFDF5] px-2 py-0.5 text-xs text-emerald-700">{currentSource === "recorded" ? "Recorded" : "AI Voice"}</span></p><audio controls className="mt-2 w-full" src={currentUrl} /><button className="mt-2 text-sm text-rose-700 underline" onClick={async () => { const { ok, d } = await save({ e164: scopeId, voicemail_greeting_url: null, voicemail_greeting_source: null }); if (ok && d?.ok) { onRemoved(); setStatus("Greeting removed."); } }}>Remove</button></div>}
    <div className="flex gap-2"><button className={`rounded px-3 py-1.5 text-sm ${tab === "ai" ? "bg-[#059669] text-white" : "bg-gray-100"}`} onClick={() => setTab("ai")}>AI Voice</button><button className={`rounded px-3 py-1.5 text-sm ${tab === "record" ? "bg-[#059669] text-white" : "bg-gray-100"}`} onClick={() => setTab("record")}>Record Your Own</button></div>
    {tab === "ai" ? <div className="space-y-2"><textarea className="w-full rounded border px-3 py-2 text-sm" rows={4} value={text} onChange={(e) => setText(e.target.value)} /><select className="w-full rounded border px-3 py-2 text-sm" value={voiceId} onChange={(e) => setVoiceId(e.target.value)}>{voices.map((v) => <option key={v.id} value={v.id}>{v.label}</option>)}</select><button className="rounded bg-[#059669] px-3 py-2 text-sm text-white" disabled={busy} onClick={async () => { setBusy(true); const { ok, d } = await gen(JSON.stringify({ e164: scopeId, text, voice_id: voiceId }), { "Content-Type": "application/json" }); setBusy(false); if (!ok || !d?.ok) return setStatus(d?.error ?? "Failed"); setPreviewUrl(d.url); setPreviewSource("polly"); setStatus("Preview generated — not live yet."); }}>Generate Preview</button></div> : <div className="space-y-2"><button className="rounded bg-gray-800 px-3 py-2 text-sm text-white" onClick={async () => { const stream = await navigator.mediaDevices.getUserMedia({ audio: true }); streamRef.current = stream; const rec = new MediaRecorder(stream); mediaRecorderRef.current = rec; const chunks: Blob[] = []; rec.ondataavailable = (e) => chunks.push(e.data); rec.onstop = () => { const blob = new Blob(chunks, { type: "audio/webm" }); setRecordingBlob(blob); if (recordingUrl) URL.revokeObjectURL(recordingUrl); setRecordingUrl(URL.createObjectURL(blob)); stream.getTracks().forEach((t) => t.stop()); }; rec.start(); setStatus("Recording..."); }}>Start Recording</button><button className="rounded bg-gray-200 px-3 py-2 text-sm" onClick={() => mediaRecorderRef.current?.stop()}>Stop</button>{recordingUrl && <audio controls className="w-full" src={recordingUrl} />}<button className="rounded bg-[#059669] px-3 py-2 text-sm text-white" disabled={!recordingBlob || busy} onClick={async () => { if (!recordingBlob) return; const f = new FormData(); f.append("e164", scopeId); f.append("audio", new File([recordingBlob], "preview.webm", { type: "audio/webm" })); setBusy(true); const { ok, d } = await gen(f); setBusy(false); if (!ok || !d?.ok) return setStatus(d?.error ?? "Failed"); setPreviewUrl(d.url); setPreviewSource("recorded"); setStatus("Preview uploaded — not live yet."); }}>Upload Preview</button></div>}
    {previewUrl && <div className="rounded-md border border-emerald-200 bg-[#ECFDF5] p-3"><p className="text-sm font-medium text-emerald-700">Preview — not live yet</p><audio controls className="mt-2 w-full" src={previewUrl} /></div>}
    <button className="rounded bg-[#059669] px-4 py-2 text-sm text-white disabled:opacity-60" disabled={!previewUrl || busy} onClick={async () => { if (!previewUrl || !previewSource) return; setBusy(true); const { ok, d } = await save({ e164: scopeId, voicemail_greeting_url: previewUrl, voicemail_greeting_source: previewSource }); setBusy(false); if (!ok || !d?.ok) return setStatus(d?.error ?? "Failed"); onSaved(previewUrl, previewSource); setPreviewUrl(null); setPreviewSource(null); setStatus("Saved as active."); }}>Save as Active Greeting</button>
    {status && <p className="text-sm text-gray-700">{status}</p>}
  </div>;
}
