"use client";
import { ChevronDown, ChevronRight } from "lucide-react";
import { useEffect, useState } from "react";
import CallRoutingEditor from "@/components/settings/phone-numbers/call-routing-editor";
import VoicemailGreetingEditor from "@/components/settings/phone-numbers/voicemail-greeting-editor";

type NumberItem = { e164: string; label: string | null; enabled: boolean; call_routing_mode: "browser_only" | "browser_first_then_forward" | "forwarding_only"; call_forwarding_number: string | null; browser_ring_timeout_seconds: number; voicemail_greeting_url: string | null; voicemail_greeting_source: "polly" | "recorded" | null };

export default function PhoneNumbersPage() { const [numbers, setNumbers] = useState<NumberItem[]>([]); const [voices, setVoices] = useState<{ id: string; label: string; engine: string }[]>([]); const [open, setOpen] = useState<Record<string, boolean>>({}); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = async () => { setLoading(true); setError(""); try { const [n, v] = await Promise.all([fetch("/api/settings/phone-system").then((r) => r.json()), fetch("/api/settings/phone-system/generate").then((r) => r.json())]); if (!n?.ok || !v?.ok) throw new Error("Failed to load settings."); setNumbers(n.numbers ?? []); setVoices(v.voices ?? []);} catch (e) { setError(e instanceof Error ? e.message : "Failed"); } finally { setLoading(false);} }; useEffect(() => { void load(); }, []);
  if (loading) return <div className="p-6">Loading...</div>; if (error) return <div className="p-6"><p className="text-rose-700">{error}</p><button onClick={load}>Retry</button></div>;
  return <div className="p-6 space-y-4">{numbers.map((n) => <div key={n.e164} className="rounded-lg border bg-white"><button className="flex w-full items-center justify-between p-4" onClick={() => setOpen((p) => ({ ...p, [n.e164]: !p[n.e164] }))}><div><p className="font-semibold">{n.e164} {n.label ? `· ${n.label}` : ""}</p><p className="text-sm text-gray-600">{n.call_routing_mode === "forwarding_only" ? `Forward → ${n.call_forwarding_number ?? "Not set"}` : `Browser · ${n.browser_ring_timeout_seconds}s`} · {n.voicemail_greeting_url ? `Custom greeting · ${n.voicemail_greeting_source === "recorded" ? "Recorded" : "AI Voice"}` : "Default greeting"}</p></div>{open[n.e164] ? <ChevronDown size={18} /> : <ChevronRight size={18} />}</button>{open[n.e164] && <div className="space-y-6 border-t p-4"><section><h3 className="mb-3 font-medium">Call Routing</h3><CallRoutingEditor scopeId={n.e164} callRoutingMode={n.call_routing_mode} browserRingTimeoutSeconds={n.browser_ring_timeout_seconds} callForwardingNumber={n.call_forwarding_number} onSaved={(next) => setNumbers((prev) => prev.map((it) => it.e164 === n.e164 ? { ...it, ...next } : it))} /></section><section><h3 className="mb-3 font-medium">Voicemail Greeting</h3><VoicemailGreetingEditor scopeId={n.e164} currentUrl={n.voicemail_greeting_url} currentSource={n.voicemail_greeting_source} voices={voices} onSaved={(url, source) => setNumbers((prev) => prev.map((it) => it.e164 === n.e164 ? { ...it, voicemail_greeting_url: url, voicemail_greeting_source: source } : it))} onRemoved={() => setNumbers((prev) => prev.map((it) => it.e164 === n.e164 ? { ...it, voicemail_greeting_url: null, voicemail_greeting_source: null } : it))} /></section></div>}</div>)}</div>;
}
